on:
  push:
    branches:
      - master

jobs:
  build_qemu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build_container
        run: ./run.sh amd64 true
      - name: build opt
        run: ./run.sh amd64 ./build.sh opt
