on: push

jobs:
  build_qemu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check merge is success
        run: bash -c 'if [ -f shazam.log ]; then echo "merge failed"; cat shazam.log; exit 1; fi'
      - name: build_container
        run: ./run.sh amd64 true
      - name: build opt
        run: ./run.sh amd64 ./build.sh opt
